spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}

  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true

  servlet:
    multipart:
     max-file-size: 8MB
     max-request-size: 8MB

    #JPA Settings
  jpa:
    hibernate.ddl_auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.springframework.security: DEBUG
  org.springframework: DEBUG
